### ISSUE TITLE
The following variables are missing: BUCKET_NAME 

### ISSUE THREAD

**Issue by EFinish** [NotCoffee418/s3-zip-upload#2]
Hi. I tried running this action. I set every variable value including `AWS_BUCKET`. However, I get the error `The following variables are missing: BUCKET_NAME ` while running.

**Comment by NotCoffee418** [comment]
Apologies, I renamed `AWS_BUCKET` to `BUCKET_NAME` but did not update the documentation. If you rename the environment key for `AWS_BUCKET` to `BUCKET_NAME`, it should work.  
Thanks for bringing it to my attention!
