### ISSUE TITLE
Does this work with all S3 providers?

### ISSUE THREAD

**Issue by TO360-IzzyDanza** [NotCoffee418/s3-zip-upload#3]
I see endpoint url is not a env parameter. Does it support other S3 providers like Wasabi, DigitalOcean, BackBlaze, etc?

**Comment by NotCoffee418** [comment]
I'm not familiar with this system but i'll see if i can implement it tomorrow.

**Comment by NotCoffee418** [comment]
Implemented 1035be03d7cdbfa1948374be8b3869b4f6b64817.  
Make sure to update your action to use NotCoffee418/s3-zip-upload@v1.1  
The environment variable is called `S3_ENDPOINT`. Note that `AWS_REGION` is still required as well.
I haven't directly tested it, though it's supported by the underlying library so it should be alright. If you do encounter any issues, let me know.

**Comment by TO360-IzzyDanza** [comment]
Cool thanks!
